spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/library-management
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
